
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: ArtifactoryCollectIssues@1
  inputs:
    artifactoryService: 'artifactory'
    configSource: 'taskConfiguration'
    taskConfig: |
      version: 1
            issues:
              trackerName: JIRA
              regexp: (.+-[0-9]+)\s-\s(.+)
              keyGroupIndex: 1
              summaryGroupIndex: 2
              trackerUrl: http://jira.jfrogchina.com:8081/issues
              aggregate: true
              aggregationStatus: RELEASED
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
