
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


- task: ArtifactoryCollectIssues@1
  inputs:
    artifactoryService: 'artifactory'
    configSource: 'taskConfiguration'
    taskConfig: |
      version: 1
      issues:
        trackerName: JIRA
        regexp: (.+-[0-9]+)\s-\s(.+)
        keyGroupIndex: 1
        summaryGroupIndex: 2
        trackerUrl: http://jira.jfrogchina.com:8081/issues
        aggregate: true
        aggregationStatus: RELEASED
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
