
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'Artifactory-V7'
    cliInstallationRepo: 'jfrog-cli'
    installExtractors: true
    extractorsInstallationRepo: 'jcenter'
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'guestbook-service/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'Artifactory-V7'
    targetResolveReleaseRepo: 'libs-release'
    targetResolveSnapshotRepo: 'libs-snapshot'
    artifactoryDeployService: 'Artifactory-V7'
    targetDeployReleaseRepo: 'libs-release'
    targetDeploySnapshotRepo: 'libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory-V7'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'Artifactory-V7'
    targetRepo: 'docker-local'
    imageName: 'guestbook'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'Artifactory-V7'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false