apiVersion: v1
kind: Service
metadata:
  name: notebook-service
  labels:
    run: notebook-service
spec:
  ports:
    - name: port3
      protocol: TCP
      port: 5555
      nodePort: 30555
  selector:
    run: notebook-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-service
  labels:
    run: notebook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: notebook-service
  template:
    metadata:
      labels:
        run: notebook-service
    spec:
      containers:
        - name: notebook-service
          image: art.local:8081/docker-local/notebook-microservices-k8s/notebook-service:latest
          env:
            - name: MYSQL_SERVER
              value: "192.168.99.100"
            - name: MYSQL_PORT
              value: "32002"
          ports:
            - containerPort: 5555
      imagePullSecrets:
      - name: regcred-local
