apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    run: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DISCOVERY_URL
              value: "http://discovery-service:8761/"
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
      imagePullSecrets:
        - name: regcred-local

