apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  labels:
    run: discovery-service
spec:
  ports:
    - name: port1
      port: 8761
      nodePort: 31002
      protocol: TCP
  selector:
    run: discovery-service
  type: NodePort
