
[code language="java"]
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/alexwang66/sample-microservices-k8s.git', credentialsId: 'wangqing-github', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('guestbook-service') {
                def app = docker.build "art.local:8081/docker/guestbook-microservices-k8s/guestbook-service:latest"
                app.push()
            }
        }

        stage ('Run') {
       //     docker.image("docker-release-local2.demo.jfrogchina.com/guestbook-microservices-k8s/guestbook-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}